language: python
python: 3.5
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py27
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: riW+phiTGXQI1FCJrrsipEoduPnQSW0uPVNR8GqPY0ew7CSYWfctNXt8hlUmmy5OI6xZg1iOozi3/0apm/yV4sTyrjfhe+D8siCKpBsPTjvmbGinsAFYRp8bm4DtQJhDYm0KnSdfsWr+GR2i1zBaan3K3cMwEuI0E/07BpRt6ejNNl0qK0lG8jqlGSevPyOOe1GsloAIOB9JlYrYPqtzmV+R9o4HWOHDdeAI180XyQ5Dgr8bb7qr0hO6bIn7vh4v1+3y09K2ai1/qlLH2jdiKjgvepfz9QWAZr2mWqPk52fULWXlsBrIpTIrarogdnYdK5o8AH8Z051soqhrN7WB4lRsG4/VZBsHvVCWPItR6kR88PhzIDYc+gnrjFTyLKBYywWEcA5uBGxd4iG9c8qqa0widgsxFbVyp+lMVoxvGjZ1oU5jbfCb/HilvAZ1bPqZveLqVrso2Wo72p3O0RVOD1TBk/AgAuNbSGqzjX3I4pLkz/xXbXBE/bKWEU4TKayP4Ap4+3SEXEXMe7pWsJIDXv7A/OZbh8qDfB6vxnaxYmiQbYypaLVFl5xitwjpuION3XaSpLhanGTydUCEnXhI9XONwMkTpEwmAesZIeEfjuhxc/OlUmEaNaYeopgzCw3ufxVpCV9n4AvcmcxsKQM7MdsXtUWnQWNMeiacnwnIrcE=
  on:
    tags: true
    repo: getslash/gadget-python
